### ISSUE TITLE
input_mask 在 CLS ， query_tokens，SEP处是0？

### ISSUE THREAD

**Issue by liuyukid** [ShannonAI/mrc-for-flat-nested-ner#1]
在 data_loader 目录下的 mrc_utils.py 中的 convert_examples_to_features 方法里：
<img width="434" alt="截屏2020-05-18 下午6 55 43" src="https://user-images.githubusercontent.com/26139664/82205437-2fa8d200-9939-11ea-95e1-06345a953450.png">
CLS ， query_tokens，SEP处的input_mask是0
那么context怎么从query_tokens处获取信息呢？
模型知道自己的问题是什么吗？

**Comment by littlesulley** [comment]
你好，我们在代码里增加了注释，可以看一下最新的代码。

**Comment by liuyukid** [comment]
好的
