### ISSUE TITLE
MRC-style preprocessed data error

### ISSUE THREAD

**Issue by Akeepers** [ShannonAI/mrc-for-flat-nested-ner#10]
下载了[google drive](https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/master/docs/data_release.md)MRC-style preprocessed data，发现并非是预处理后的数据， & 利用[预处理脚本](https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/master/data/data_generate/preprocess_data.py)处理时会出错

**Comment by stepperL** [comment]
您好，我们5月1日之前会把所有数据都release出来。

**Comment by Akeepers** [comment]
好的，期待
