### ISSUE TITLE
question about queries for Eng-OntoNotes5.0

### ISSUE THREAD

**Issue by iamhere1** [ShannonAI/mrc-for-flat-nested-ner#15]
您好，请问下您 Eng-OntoNotes5.0 这个数据集对应的query哪里可以看到吗？谢谢！

**Comment by ghost** [comment]
您好，北京时间6月3号晚上12点之前，我会把所有的query更新到`https://github.com/ShannonAI/mrc-for-flat-nested-ner/tree/master/data_preprocess/queries`文件夹下面。
更新完成再通知您，谢谢！

**Comment by iamhere1** [comment]
好的，非常感谢您的分享！

**Comment by ghost** [comment]
英文Onotnotes5.0的query在这里  `https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/fea/query-for-en-onto5/data_preprocess/queries/en_ontonotes5.json`.
如果还有其他问题，欢迎随时提问！谢谢

**Comment by iamhere1** [comment]
好的，谢谢您！

**Comment by ghost** [comment]
您好，之前的链接失效了。Ontonotes 的query麻烦参考这个`https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/master/data_preprocess/queries/en_ontonotes5.json`。

**Comment by iamhere1** [comment]
好的，谢谢
