### ISSUE TITLE
一个问句对应多个answer的情况

### ISSUE THREAD

**Issue by zhangatao** [ShannonAI/mrc-for-flat-nested-ner#18]
你好，这个模型是否支持，在同一个question下面，出现多个答案的情况，如果出现了多个答案，是否可以能够全部的提取出来，谢谢🙏

**Comment by littlesulley** [comment]
您好，同一个question对应多个answer的意思是？可以举个例子嘛？

**Comment by littlesulley** [comment]
您好，感谢提问。是可以支持一个问题多回答的。 

模型 先识别所有的 start, 所有的end， 然后将 start 和 end 组合起来成为 answer。
模型是支持 一个句子里面 多start，多end的， 组合之后就是多个 answer了
