### ISSUE TITLE
missing ``utils.ner_evaluate''?

### ISSUE THREAD

**Issue by LorrinWWW** [ShannonAI/mrc-for-flat-nested-ner#2]
We are trying to reproduce the experiments, however, we found it said cannot import ``utils.ner_evaluate''? looks like missing some file? thx!

**Comment by yahshibu** [comment]
In addition to the above, I've found the following files are missing.

- data/apply_text_norm
- data/ner_dataset_processor
- data/query_ner_data_processor
- data/data_generate/query_map
- data/data_generate/tagging_utils
- layers/bert_basic_model
- layers/math_funcs
- utils/ner_evaluate

These files are being referred to but don't exist.

**Comment by stepperL** [comment]
I will update the repo after this week. Thanks for your patience.
