### ISSUE TITLE
Bug in BMOES sequence decoding

### ISSUE THREAD

**Issue by dt-ahmed-touila** [ShannonAI/mrc-for-flat-nested-ner#22]
Bug in [bmes_decode](https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/cbe97ed5d03675260eff15244ebe5b28e8b6b693/metric/flat_span_f1.py#L119) function, infinite loop encountered when predictions presented certain patterns (Exp: O-O-O-M-E). 

On prediction output and in the first iterations of training such sequences are not impossible to get which leads to an infinite evaluation time. 

Quick fix: add an `idx+=1` in [line](https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/cbe97ed5d03675260eff15244ebe5b28e8b6b693/metric/flat_span_f1.py#L153)

**Comment by ghost** [comment]
Thanks for pointing that out! 
I just made an update. Closing the issue.
