### ISSUE TITLE
关于 span_loss 的负例构建

### ISSUE THREAD

**Issue by xilinniao123** [ShannonAI/mrc-for-flat-nested-ner#24]
您好：
感谢分享！ 对于每个样本（假设长度为n），该样本中每个位置和其他位置构建一个矩阵（n,n），该样本中出现的实体利用其位置在矩阵填充为1，其余都是填充为0。请问我对于这个负例的构建理解正确吗？
第二个问题，如果是这样的，那么负例是不是太多？

**Comment by littlesulley** [comment]
感谢提问
1、你说的是对的。
2、负例多不会有大问题，只要和 test 的distribution 一致就可以。
