### ISSUE TITLE
关于flat ner的指标问题

### ISSUE THREAD

**Issue by xueyouluo** [ShannonAI/mrc-for-flat-nested-ner#3]
![image](https://user-images.githubusercontent.com/5196100/82537895-6a9b4780-9b7d-11ea-9d85-2842f9b8929f.png)

这里Glyce-BERT的precision和recall都是大于81的，为什么f1只有80多？

**Comment by littlesulley** [comment]
nice catch ！实在抱歉。  glyce 那篇文章更新结果的时候，忘记更新 F1 了。我们就直接 copy 过来了。 我们这就修改一下文章和 repo。非常感谢反馈。
