### ISSUE TITLE
您好，span_loss 收益大吗？

### ISSUE THREAD

**Issue by Clitost** [ShannonAI/mrc-for-flat-nested-ner#4]
我发现doc_span_pos很容易导致内存溢出，这部分主要是用来计算sapn_loss的，这部分损失对于整体效果收益大吗？

**Comment by littlesulley** [comment]
你好，这个损失很是重要的。比如你预测了[1,2,3]是start， [4,5,6]是end，但是合法的span只有(1,5),(2,6)，没有这个span loss的话模型就没有办法找到正确的span了。

**Comment by Clitost** [comment]
十分感谢！
