### ISSUE TITLE
Cannot import TensorMetric

### ISSUE THREAD

**Issue by minstar** [ShannonAI/mrc-for-flat-nested-ner#54]
My pytorch-lightning version is 0.10.0
and I think the version has been updated thus cannot import TensorMetric in metrics.query_span_f1.py
So, may I ask for the environment details of your experiment?

**Comment by YuxianMeng** [comment]
> My pytorch-lightning version is 0.10.0
> and I think the version has been updated thus cannot import TensorMetric in metrics.query_span_f1.py
> So, may I ask for the environment details of your experiment?

pytorch-lightning==0.9.0 should work. We have updated the requirements.txt, and thanks for your feedback!

**Comment by minstar** [comment]
Thank you for your fast reply!
