### ISSUE TITLE
想问一下在使用多个GPU的时候，batch_size的问题..

### ISSUE THREAD

**Issue by xuanzebi** [ShannonAI/mrc-for-flat-nested-ner#58]
lighting官网上写的是batch_size大小 是gpus * batch_size
![image](https://user-images.githubusercontent.com/26642184/96545692-741b0e00-12db-11eb-8593-d7eeaf094d1f.png)

但是在实际使用的时候，使用ddp 进行训练 三个卡和一个卡的batch_size是一样大的.. 用三个卡增大batch_size进行训练会爆显存不足，不知道遇到过这个问题吗

**Comment by YuxianMeng** [comment]
注意不要在其它地方设置环境变量如CUDA_VISIBLE_DEVICES，只用pytorch-lightning的n-gpus参数设置就没有问题
