### ISSUE TITLE
Question about sentence truncation

### ISSUE THREAD

**Issue by yhcc** [ShannonAI/mrc-for-flat-nested-ner#7]
Thank you for publishing the source code immediately, I have some concerns about the pre-processing. Based on https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/759b7311348efccfb41e6c6529e8620d8d599aa4/data_loader/mrc_utils.py#L156 , the code will truncate sentence after the `max_tokens_for_doc`, whether this truncation is also conducted in the test set?

**Comment by littlesulley** [comment]
this is a great question and sorry about the confusion. Actually there is no problem with the implementation. 

max_tokens_for_doc is set to config.max_seq_length, which is one of the the intial input parameter meter to the model, with default value set to 128. 

https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/759b7311348efccfb41e6c6529e8620d8d599aa4/data_loader/mrc_data_loader.py#L35

https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/759b7311348efccfb41e6c6529e8620d8d599aa4/run/train_bert_mrc.py#L42

We actually calculated  config.max_seq_length for different datasets in advance, set to 
max(max_len_train, max_len_dev, max_len_test)

As you can see from the log, we pre-compute the max_seq_length
https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/master/log/en_ace04.txt#L25

The reason why we keep the variable max_seq_length is just to accomendate to the BERT setup. 

Thank you so much for the suggestion. We will clear this confusion in the code.

**Comment by yhcc** [comment]
Although the influenced samples should be very rare, the longest sequence (After bert-base-cased BPE) in conll2003 test is 146, it seems like the pre-set 150 is not enough to cover this sample (I believe this should not change the performance).

**Comment by littlesulley** [comment]
Thanks for the comment !! We will update the code as soon as possible.
