### ISSUE TITLE
start_outputs和end_outputs维度问题 

### ISSUE THREAD

**Issue by lxgend** [ShannonAI/mrc-for-flat-nested-ner#72]
https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/5a2a52690a89baae87cfe8138eed74c57ba60606/models/bert_query_ner.py#L18

请教一下，
nn.Linear(config.hidden_size, 1) 中的1，代表什么意思？
这个维度设定为1或者2，分别有什么考量？

非常迷惑，烦请解答，谢谢

**Comment by YuxianMeng** [comment]
@lxgend 输出维度1+sigmoid和输出维度2+softmax都可以做二分类，区别应该不大
