### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by Gavin4th** [ShannonAI/mrc-for-flat-nested-ner#74]
您好，我在自己提出的语料库上跑实验，程序能正常运行，但是迭代一会后会出现key - error，请问大致是什么问题了
![image](https://user-images.githubusercontent.com/22930496/110773300-8cde8d00-8297-11eb-90af-7824a7f3c6d1.png)

![image](https://user-images.githubusercontent.com/22930496/110773264-83edbb80-8297-11eb-8066-318d67db0ad8.png)

**Comment by currylym** [comment]
hi你好 @Gavin4th ，我也碰到了这个问题，请问解决了吗

**Comment by YuxianMeng** [comment]
@Gavin4th @currylym Hi，因为我手头没有你们的数据，不方便复现这个bug。我的建议是检查一下报错的样本是否包含特殊的字符，从而导致offsets没有对齐。另外注意如果是中文文本，需要在dataset里传入参数`is_chinese=True`
