### ISSUE TITLE
span_loss_candidates参数的问题

### ISSUE THREAD

**Issue by ISGuXing** [ShannonAI/mrc-for-flat-nested-ner#76]
您好，请问span_loss_candidates参数我使用all发现没有收敛，使用gold才收敛，大概训练了30个epoch，在test集上只有52%的F1，请问这个参数为什么这么重要呢？大概训练多少个epoch才会收敛到比较好的一个效果呢？期待您的回复！
（我是在bert_base_case上训练的，然后计算span的时候用了您代码中的 MultiNonLinearClassifier）

**Comment by YuxianMeng** [comment]
@ISGuXing Hi，`span_loss_candidates=all`会导致负例数量远远大于正例。这种正负样本不均衡的问题会对模型的训练造成比较大的影响，后续我们有[尝试dice-loss解决这个问题，你可以借鉴一下这个repo](https://github.com/ShannonAI/dice_loss_for_NLP)
