### ISSUE TITLE
Some details in MRCNERDataset

### ISSUE THREAD

**Issue by smiles724** [ShannonAI/mrc-for-flat-nested-ner#79]
Hi, I am a little confused about why you add one to all ending position indices as `end_positions = [x + 1 for x in end_positions]`. Can you please give me an explanation?

**Comment by YuxianMeng** [comment]
@Wufang1997 This is a variable used to store char-level end positions in python style: `range(start, end)` do not contain `end`. The variable is further used to compute final start/end labels considering query+context inputs and wordpiece tokenizer.

**Comment by smiles724** [comment]
> @Wufang1997 This is a variable used to store char-level end positions in python style: `range(start, end)` do not contain `end`. The variable is further used to compute final start/end labels considering query+context inputs and wordpiece tokenizer.

Thanks, I also figured it out myself!
