### ISSUE TITLE
BCELoss无效，DiceLoss可以

### ISSUE THREAD

**Issue by EeyoreLee** [ShannonAI/mrc-for-flat-nested-ner#87]
当我选择BCELoss时，loss确实也可以收敛，但是F1 score都是0 。我确定F1的计算方式是没问题的，因为我看了输出的logits，都是负值，意味着预测的都是O标签。
但是我只是将loss functional 改成 DiceLoss的时候，一切正常work了。我不知道问题出在哪里，我没有直接使用该仓库的代码，如果有需要，我可以贴上我的脚本。

**Comment by Senwang98** [comment]
@EeyoreLee 
本仓库的代码精度能对齐论文精度吗，我尝试了6个数据集，一般会相差1个点

**Comment by 3-rd** [comment]
> @EeyoreLee 本仓库的代码精度能对齐论文精度吗，我尝试了6个数据集，一般会相差1个点

你好，请问你有尝试复现过文中zero-shot的实验吗 就是在conll03上训练 用ontonote 5.0测试，我完全无法复现论文的效果。（其他数据集上的实验是正常的）

**Comment by EeyoreLee** [comment]
我记得当时4个ner数据都复现成功了
