### ISSUE TITLE
Convert data from conll type to mrc type

### ISSUE THREAD

**Issue by Toan-it-mta** [ShannonAI/mrc-for-flat-nested-ner#98]
i have 1 dataset which is formatted similar to conll3 dataset. How can I convert this to mrc format so that the model can be read. Thanks!!

**Comment by zhanghaok** [comment]
> i have 1 dataset which is formatted similar to conll3 dataset. How can I convert this to mrc format so that the model can be read. Thanks!!

Hello, did you solve this problem, I encountered the same problem, how did you solve it?

**Comment by Toan-it-mta** [comment]
> > >i have 1 dataset which is formatted similar to conll3 dataset. How can I convert this to mrc format so that the model can be read. Thanks!!
> >
> >Hello, did you solve this problem, I encountered the same problem, how did you solve it?

I write a piece of code to solve them. It's below.

[conll2mrc](https://drive.google.com/file/d/1ZLB84rNSKqWK1cIeX_9dCw8Pk4UorKv1/view?usp=sharing)

please reply me if it works well

**Comment by zhanghaok** [comment]
> > > > i have 1 dataset which is formatted similar to conll3 dataset. How can I convert this to mrc format so that the model can be read. Thanks!!
> > > 
> > > 
> > > Hello, did you solve this problem, I encountered the same problem, how did you solve it?
> 
> I write a piece of code to solve them. It's below.
> 
> [conll2mrc](https://drive.google.com/file/d/1ZLB84rNSKqWK1cIeX_9dCw8Pk4UorKv1/view?usp=sharing)
> 
> please reply me if it works well

yead, this code is great and it has worked!Thank u very much~~~~😁
